from math import pi

G = 6
RATIO = 0.25
WINDOW_WIDTH = 1080
WINDOW_HEIGHT = 840
CART_WIDTH = 140
CART_HEIGHT = 100
INVADER_WIDTH = 70
INVADER_HEIGHT = 70
BULLET_RADIUS = 30
INTERVAL_FOR_SCORE = 1000
CAN_MOVE_DOWN = False
AIM_CART = 'AIM_CART'
BAD_AIM_CART = 'BAD_AIM_CART'
AIM_RANDOM = 'AIM_RANDOM'
RIGHT = "RIGHT"
LEFT = "LEFT"
NOPE = "NOPE"
INTERVAL_FOR_INVADERS = 2000
BUNKERS_COUNT = 5
